package africa.growtogether.platform.eip;
import africa.growtogether.platform.common.security.EnterpriseIdentityContext; import static africa.growtogether.platform.eip.EipGatewayDtos.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class EipGatewayService {private final EnterpriseIdentityContext identity;private final GatewayRouteRepository routes;private final WebhookSubscriptionRepository webhooks;private final TransformationRuleRepository transforms;private final ExternalConnectorRepository connectors;private final IntegrationCredentialCrypto crypto;
 public EipGatewayService(EnterpriseIdentityContext identity,GatewayRouteRepository routes,WebhookSubscriptionRepository webhooks,TransformationRuleRepository transforms,ExternalConnectorRepository connectors,IntegrationCredentialCrypto crypto){this.identity=identity;this.routes=routes;this.webhooks=webhooks;this.transforms=transforms;this.connectors=connectors;this.crypto=crypto;}
 @Transactional public GatewayRouteView createRoute(GatewayRouteCommand c){return GatewayRouteView.from(routes.save(new GatewayRoute(identity.tenantId(),c.routeCode(),c.pathPattern(),c.httpMethod(),c.upstreamUri(),c.requiredAuthority(),c.rateLimitPerMinute(),c.timeoutMillis())));}
 @Transactional(readOnly=true) public List<GatewayRouteView> listRoutes(){return routes.findByTenantIdOrderByRouteCode(identity.tenantId()).stream().map(GatewayRouteView::from).toList();}
 @Transactional public WebhookView createWebhook(WebhookCommand c){return WebhookView.from(webhooks.save(new WebhookSubscription(identity.tenantId(),c.subscriptionCode(),c.eventPattern(),c.callbackUrl(),crypto.encrypt(c.signingSecret()),crypto.keyId())));}
 @Transactional(readOnly=true) public List<WebhookView> listWebhooks(){return webhooks.findByTenantIdOrderBySubscriptionCode(identity.tenantId()).stream().map(WebhookView::from).toList();}
 @Transactional public TransformationView createTransform(TransformCommand c){return TransformationView.from(transforms.save(new TransformationRule(identity.tenantId(),c.ruleCode(),c.sourceContentType(),c.targetContentType(),c.mappingExpression())));}
 @Transactional(readOnly=true) public List<TransformationView> listTransforms(){return transforms.findByTenantIdOrderByRuleCode(identity.tenantId()).stream().map(TransformationView::from).toList();}
 @Transactional public ConnectorView createConnector(ConnectorCommand c){String cipher=crypto.encrypt(c.credential());return ConnectorView.from(connectors.save(new ExternalConnector(identity.tenantId(),c.connectorCode(),c.connectorType(),c.baseUrl(),c.authType(),cipher,cipher==null?null:crypto.keyId())));}
 @Transactional(readOnly=true) public List<ConnectorView> listConnectors(){return connectors.findByTenantIdOrderByConnectorCode(identity.tenantId()).stream().map(ConnectorView::from).toList();}
}
