package africa.growtogether.platform.eiam.mfa;
import africa.growtogether.platform.common.security.GtPrincipal; import africa.growtogether.platform.eiam.auth.*; import africa.growtogether.platform.eiam.user.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class MfaService {
 private final MfaProfileRepository profiles; private final MfaRecoveryCodeRepository recoveryCodes; private final MfaChallengeRepository challenges; private final TrustedDeviceRepository devices; private final UserAccountRepository users; private final UserSessionRepository sessions; private final TotpService totp; private final MfaCryptoService crypto; private final MfaProperties props; private final SecureRandom random=new SecureRandom();
 public MfaService(MfaProfileRepository profiles,MfaRecoveryCodeRepository recoveryCodes,MfaChallengeRepository challenges,TrustedDeviceRepository devices,UserAccountRepository users,UserSessionRepository sessions,TotpService totp,MfaCryptoService crypto,MfaProperties props){this.profiles=profiles;this.recoveryCodes=recoveryCodes;this.challenges=challenges;this.devices=devices;this.users=users;this.sessions=sessions;this.totp=totp;this.crypto=crypto;this.props=props;}
 @Transactional public EnrollmentResponse enroll(){GtPrincipal p=principal();String secret=totp.generateSecret();MfaProfile profile=profiles.findByTenantIdAndUserId(p.tenantId(),p.userId()).orElseGet(()->{MfaProfile x=new MfaProfile(p.userId(),crypto.encrypt(secret));x.setTenantId(p.tenantId());return x;}); if(profile.isEnabled())throw new MfaException("MFA is already enabled."); if(profile.getId()!=null) throw new MfaException("A pending MFA enrollment already exists; disable or complete it."); profiles.save(profile); List<String> codes=replaceRecoveryCodes(p.tenantId(),p.userId());String uri="otpauth://totp/GrowTogether:"+p.username()+"?secret="+secret+"&issuer=GrowTogether&digits=6&period=30";return new EnrollmentResponse(secret,uri,codes);}
 @Transactional public void verifyEnrollment(VerifyEnrollmentCommand c){GtPrincipal p=principal();MfaProfile profile=profiles.findByTenantIdAndUserId(p.tenantId(),p.userId()).orElseThrow(()->new MfaException("MFA enrollment was not found."));if(profile.isEnabled())return;if(!totp.verify(crypto.decrypt(profile.getEncryptedTotpSecret()),c.code(),Instant.now()))throw new MfaException("The verification code is invalid.");profile.enable(Instant.now());}
 @Transactional public void disable(DisableMfaCommand c){GtPrincipal p=principal();MfaProfile profile=profiles.findByTenantIdAndUserId(p.tenantId(),p.userId()).orElseThrow(()->new MfaException("MFA is not enabled."));if(!verifyCode(profile,p.tenantId(),p.userId(),c.code(),null))throw new MfaException("The verification code is invalid.");profile.disable();recoveryCodes.deleteForUser(p.tenantId(),p.userId());sessions.revokeAllForUser(p.tenantId(),p.userId(),"MFA_DISABLED",Instant.now());}
 public boolean enabled(UUID tenant,UUID user){return profiles.findByTenantIdAndUserId(tenant,user).map(MfaProfile::isEnabled).orElse(false);}
 @Transactional public MfaChallengeResponse createChallenge(UUID tenant,UUID user){String raw=token();Instant exp=Instant.now().plusSeconds(props.challengeSeconds());MfaChallenge c=new MfaChallenge(user,hash(raw),exp);c.setTenantId(tenant);challenges.save(c);return new MfaChallengeResponse(true,raw,exp);}
 @Transactional public UUID consumeChallenge(String raw,String code,String recovery){Instant now=Instant.now();MfaChallenge c=challenges.findByChallengeHash(hash(raw)).orElseThrow(()->new MfaException("MFA challenge is invalid or expired."));MfaProfile p=profiles.findByTenantIdAndUserId(c.getTenantId(),c.getUserId()).orElseThrow(()->new MfaException("MFA profile is unavailable."));if(!verifyCode(p,c.getTenantId(),c.getUserId(),code,recovery))throw new MfaException("MFA verification failed.");if(!c.consume(now))throw new MfaException("MFA challenge is invalid or expired.");p.verified(now);return c.getUserId();}
 @Transactional public Optional<TrustedDeviceCredential> trust(UUID tenant,UUID user,String name,String fingerprint){if(name==null||name.isBlank()||fingerprint==null||fingerprint.isBlank())return Optional.empty();String raw=token();Instant now=Instant.now(),exp=now.plusSeconds(props.trustedDeviceSeconds());TrustedDevice d=new TrustedDevice(user,hash(raw),name.trim(),hash(fingerprint),exp,now);d.setTenantId(tenant);devices.save(d);return Optional.of(new TrustedDeviceCredential(raw,exp));}
 @Transactional public boolean isTrusted(UUID tenant,UUID user,String raw,String fingerprint){if(raw==null||raw.isBlank()||fingerprint==null||fingerprint.isBlank())return false;return devices.findByTokenHash(hash(raw)).filter(d->d.getTenantId().equals(tenant)&&d.getUserId().equals(user)).map(d->d.trust(hash(fingerprint),Instant.now())).orElse(false);}
 public List<TrustedDeviceView> listDevices(){GtPrincipal p=principal();return devices.findAllByTenantIdAndUserIdOrderByCreatedAtDesc(p.tenantId(),p.userId()).stream().map(TrustedDeviceView::from).toList();}
 @Transactional public void revokeDevice(UUID id){GtPrincipal p=principal();TrustedDevice d=devices.findByIdAndTenantIdAndUserId(id,p.tenantId(),p.userId()).orElseThrow(()->new MfaException("Trusted device was not found."));d.revoke(Instant.now());}
 private boolean verifyCode(MfaProfile p,UUID tenant,UUID user,String code,String recovery){if(code!=null&&totp.verify(crypto.decrypt(p.getEncryptedTotpSecret()),code,Instant.now()))return true;if(recovery==null||recovery.isBlank())return false;return recoveryCodes.findByTenantIdAndUserIdAndCodeHash(tenant,user,hash(recovery)).map(c->c.use(Instant.now())).orElse(false);}
 private List<String> replaceRecoveryCodes(UUID tenant,UUID user){recoveryCodes.deleteForUser(tenant,user);List<String> raw=new ArrayList<>();for(int i=0;i<10;i++){String c=randomCode();raw.add(c);MfaRecoveryCode e=new MfaRecoveryCode(user,hash(c));e.setTenantId(tenant);recoveryCodes.save(e);}return List.copyOf(raw);}
 private String randomCode(){byte[] b=new byte[9];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b).toUpperCase(Locale.ROOT);}
 private String token(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private GtPrincipal principal(){Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal();if(p instanceof GtPrincipal g)return g;throw new MfaException("Authentication is required.");}
}
