package africa.growtogether.platform.eap;

import africa.growtogether.platform.common.security.EnterpriseIdentityContext;
import africa.growtogether.platform.eap.integration.*;
import com.fasterxml.jackson.databind.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;

@Service
public class AnalyticsProcessingService {
 private final EnterpriseIdentityContext identity; private final EapConfigurationGateway configuration; private final EapAuditRecorder audit; private final AnalyticsEventRepository events; private final MetricDefinitionRepository definitions; private final MetricAggregateRepository aggregates; private final DashboardDefinitionRepository dashboards; private final ReportExecutionRepository reports; private final ObjectMapper mapper;
 public AnalyticsProcessingService(EnterpriseIdentityContext identity,EapConfigurationGateway configuration,EapAuditRecorder audit,AnalyticsEventRepository events,MetricDefinitionRepository definitions,MetricAggregateRepository aggregates,DashboardDefinitionRepository dashboards,ReportExecutionRepository reports,ObjectMapper mapper){this.identity=identity;this.configuration=configuration;this.audit=audit;this.events=events;this.definitions=definitions;this.aggregates=aggregates;this.dashboards=dashboards;this.reports=reports;this.mapper=mapper;}
 @Transactional public UUID ingest(EapDtos.IngestEvent request){var event=events.save(new AnalyticsEvent(identity.requireTenantId(),request.eventType(),request.sourceService(),request.correlationId(),request.eventTime(),request.payloadJson()));audit.success("ANALYTICS.EVENT.INGESTED","ANALYTICS_EVENT",event.getId().toString(),"Analytics event ingested",Map.of("eventType",request.eventType(),"sourceService",request.sourceService()));return event.getId();}
 @Transactional public UUID createMetric(EapDtos.CreateMetric request){UUID tenant=identity.requireTenantId();if(definitions.findByTenantIdAndMetricCode(tenant,request.code().toUpperCase(Locale.ROOT)).isPresent())throw new IllegalStateException("Metric code already exists");return definitions.save(new MetricDefinition(tenant,request.code(),request.name(),request.eventType(),request.type(),request.period(),request.valuePath(),request.dimensionPathsJson())).getId();}
 @Transactional public int processReceived(int maxAttempts){UUID tenant=identity.requireTenantId();int effectiveAttempts=maxAttempts>0?maxAttempts:configuration.maximumAttempts();int processed=0;for(AnalyticsEvent event:events.findTop100ByTenantIdAndProcessingStatusOrderByEventTimeAsc(tenant,AnalyticsEnums.EventStatus.RECEIVED)){event.begin();try{JsonNode payload=mapper.readTree(event.payloadJson());for(MetricDefinition definition:definitions.findByTenantIdAndEventTypeAndActiveTrue(tenant,event.eventType()))aggregate(tenant,definition,event,payload);event.complete();processed++;}catch(Exception ex){event.fail(ex.getMessage()==null?ex.getClass().getSimpleName():ex.getMessage(),effectiveAttempts);}}audit.success("ANALYTICS.PROCESSING.COMPLETED","ANALYTICS_BATCH",tenant.toString(),"Analytics batch processed",Map.of("processed",processed));return processed;}
 private void aggregate(UUID tenant,MetricDefinition definition,AnalyticsEvent event,JsonNode payload)throws Exception{Instant start=bucketStart(event.eventTime(),definition.aggregationPeriod());Instant end=bucketEnd(start,definition.aggregationPeriod());String dimensions="{}";String hash=hex(MessageDigest.getInstance("SHA-256").digest(dimensions.getBytes(StandardCharsets.UTF_8)));MetricAggregate aggregate=aggregates.findByTenantIdAndMetricCodeAndBucketStartAndDimensionHash(tenant,definition.metricCode(),start,hash).orElseGet(()->new MetricAggregate(tenant,definition.metricCode(),start,end,hash,dimensions));BigDecimal value=definition.metricType()==AnalyticsEnums.MetricType.COUNTER?BigDecimal.ONE:extractNumber(payload,null);aggregate.add(value);aggregates.save(aggregate);}
 private BigDecimal extractNumber(JsonNode payload,String path){if(path==null||path.isBlank())return BigDecimal.ONE;JsonNode node=payload.at(path.startsWith("/")?path:"/"+path.replace('.', '/'));return node.isNumber()?node.decimalValue():BigDecimal.ZERO;}
 @Transactional(readOnly=true) public List<EapDtos.MetricPoint> metric(String code,Instant from,Instant to){return aggregates.findByTenantIdAndMetricCodeAndBucketStartBetweenOrderByBucketStart(identity.requireTenantId(),code.toUpperCase(Locale.ROOT),from,to).stream().map(a->new EapDtos.MetricPoint(a.bucketStart(),a.sampleCount(),a.sumValue(),a.average())).toList();}
 @Transactional public UUID createDashboard(EapDtos.CreateDashboard request){return dashboards.save(new DashboardDefinition(identity.requireTenantId(),request.code(),request.name(),request.widgetConfigurationJson())).getId();}
 @Transactional(readOnly=true) public EapDtos.DashboardRuntime dashboard(String code,Instant from,Instant to){DashboardDefinition dashboard=dashboards.findByTenantIdAndDashboardCode(identity.requireTenantId(),code.toUpperCase(Locale.ROOT)).orElseThrow();Map<String,List<EapDtos.MetricPoint>> data=new LinkedHashMap<>();try{JsonNode widgets=mapper.readTree(dashboard.widgetConfigurationJson());if(widgets.isArray())for(JsonNode widget:widgets){String metric=widget.path("metricCode").asText();if(!metric.isBlank())data.put(metric,metric(metric,from,to));}}catch(Exception e){throw new IllegalStateException("Invalid dashboard configuration",e);}return new EapDtos.DashboardRuntime(dashboard.dashboardCode(),dashboard.widgetConfigurationJson(),data);}
 @Transactional public EapDtos.ReportResult requestReport(EapDtos.RequestReport request){ReportExecution execution=reports.save(new ReportExecution(identity.requireTenantId(),request.reportCode(),request.parametersJson(),request.format()));return new EapDtos.ReportResult(execution.getId(),execution.reportStatus(),execution.artifactReference());}
 private static Instant bucketStart(Instant t,AnalyticsEnums.AggregationPeriod p){ZonedDateTime z=t.atZone(ZoneOffset.UTC);return switch(p){case MINUTE->t.truncatedTo(ChronoUnit.MINUTES);case HOUR->t.truncatedTo(ChronoUnit.HOURS);case DAY->z.toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant();case WEEK->z.toLocalDate().minusDays(z.getDayOfWeek().getValue()-1L).atStartOfDay(ZoneOffset.UTC).toInstant();case MONTH->z.withDayOfMonth(1).toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant();};}
 private static Instant bucketEnd(Instant s,AnalyticsEnums.AggregationPeriod p){return switch(p){case MINUTE->s.plus(1,ChronoUnit.MINUTES);case HOUR->s.plus(1,ChronoUnit.HOURS);case DAY->s.plus(1,ChronoUnit.DAYS);case WEEK->s.plus(7,ChronoUnit.DAYS);case MONTH->s.atZone(ZoneOffset.UTC).plusMonths(1).toInstant();};}
 private static String hex(byte[] b){return java.util.HexFormat.of().formatHex(b);}
}
