package africa.growtogether.platform.eap;
import africa.growtogether.platform.common.persistence.AuditedTenantEntity;
import jakarta.persistence.*; import java.time.Instant;
@Entity @Table(name="eap_report_executions",indexes=@Index(name="ix_eap_report_status",columnList="tenant_id,report_status,requested_at"))
public class ReportExecution extends AuditedTenantEntity {
 @Column(name="report_code",nullable=false,length=120) private String reportCode; @Column(name="parameters_json",columnDefinition="text") private String parametersJson; @Enumerated(EnumType.STRING) @Column(name="export_format",nullable=false,length=20) private AnalyticsEnums.ExportFormat exportFormat; @Enumerated(EnumType.STRING) @Column(name="report_status",nullable=false,length=20) private AnalyticsEnums.ReportStatus reportStatus=AnalyticsEnums.ReportStatus.QUEUED; @Column(name="requested_at",nullable=false) private Instant requestedAt=Instant.now(); @Column(name="completed_at") private Instant completedAt; @Column(name="artifact_reference",length=500) private String artifactReference; @Column(name="failure_reason",columnDefinition="text") private String failureReason;
 protected ReportExecution(){} public ReportExecution(java.util.UUID tenantId,String code,String params,AnalyticsEnums.ExportFormat format){setTenantId(tenantId);reportCode=req(code);parametersJson=params;exportFormat=format==null?AnalyticsEnums.ExportFormat.JSON:format;} private static String req(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("value is required");return v.trim();}
 public void start(){if(reportStatus!=AnalyticsEnums.ReportStatus.QUEUED)throw new IllegalStateException("Report is not queued");reportStatus=AnalyticsEnums.ReportStatus.RUNNING;} public void complete(String artifact){if(reportStatus!=AnalyticsEnums.ReportStatus.RUNNING)throw new IllegalStateException("Report is not running");artifactReference=req(artifact);completedAt=Instant.now();reportStatus=AnalyticsEnums.ReportStatus.COMPLETED;} public void fail(String reason){if(reportStatus!=AnalyticsEnums.ReportStatus.RUNNING)throw new IllegalStateException("Report is not running");failureReason=req(reason);completedAt=Instant.now();reportStatus=AnalyticsEnums.ReportStatus.FAILED;}
 public AnalyticsEnums.ReportStatus reportStatus(){return reportStatus;} public String artifactReference(){return artifactReference;}
}
