package africa.growtogether.platform.eiam.auth;
import africa.growtogether.platform.common.security.*; import africa.growtogether.platform.common.web.RequestContextHolder; import africa.growtogether.platform.eiam.mfa.*; import africa.growtogether.platform.eiam.permission.EffectiveAuthorityService; import africa.growtogether.platform.eiam.user.*; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AuthenticationService {
 private final UserAccountRepository users; private final UserSessionRepository sessions; private final PasswordService passwords; private final EffectiveAuthorityService authorities; private final JwtService jwt; private final JwtProperties jwtProps; private final AuthProperties props; private final RefreshTokenService refreshTokens; private final MfaService mfa;
 public AuthenticationService(UserAccountRepository users,UserSessionRepository sessions,PasswordService passwords,EffectiveAuthorityService authorities,JwtService jwt,JwtProperties jwtProps,AuthProperties props,RefreshTokenService refreshTokens,MfaService mfa){this.users=users;this.sessions=sessions;this.passwords=passwords;this.authorities=authorities;this.jwt=jwt;this.jwtProps=jwtProps;this.props=props;this.refreshTokens=refreshTokens;this.mfa=mfa;}
 @Transactional public LoginResponse login(LoginCommand cmd){UUID tenant=tenant();Instant now=Instant.now();UserAccount u=findUser(tenant,cmd.usernameOrEmail());if(!u.canAuthenticateAt(now))throw new AuthenticationException("Account is not available for authentication.");if(!passwords.matches(cmd.password(),u.getPasswordHash())){u.recordFailedLogin(now,props.maxFailedAttempts(),props.lockSeconds());throw new AuthenticationException("Invalid username or password.");}u.recordSuccessfulLogin(now);if(mfa.enabled(tenant,u.getId())){boolean trusted=mfa.isTrusted(tenant,u.getId(),cmd.trustedDeviceToken(),cmd.deviceFingerprint());if(!trusted){var challenge=mfa.createChallenge(tenant,u.getId());return LoginResponse.challenge(challenge.challengeToken(),challenge.expiresAt());}return LoginResponse.authenticated(issue(u,null,now,true,true),null,null);}return LoginResponse.authenticated(issue(u,null,now,false,false),null,null);}
 @Transactional public LoginResponse completeMfa(MfaLoginCommand cmd){UUID userId=mfa.consumeChallenge(cmd.challengeToken(),cmd.code(),cmd.recoveryCode());UUID tenant=tenant();UserAccount u=users.findByIdAndTenantId(userId,tenant).orElseThrow(()->new AuthenticationException("Session user is unavailable."));var credential=cmd.trustDevice()?mfa.trust(tenant,userId,cmd.deviceName(),cmd.deviceFingerprint()):Optional.<TrustedDeviceCredential>empty();TokenResponse tokens=issue(u,null,Instant.now(),true,credential.isPresent());return LoginResponse.authenticated(tokens,credential.map(TrustedDeviceCredential::token).orElse(null),credential.map(TrustedDeviceCredential::expiresAt).orElse(null));}
 @Transactional public TokenResponse refresh(RefreshCommand cmd){Instant now=Instant.now();UserSession s=sessions.findByRefreshTokenHash(refreshTokens.hash(cmd.refreshToken())).orElseThrow(()->new AuthenticationException("Refresh token is invalid."));if(!s.usableAt(now))throw new AuthenticationException("Refresh token is expired or revoked.");UserAccount u=users.findByIdAndTenantId(s.getUserId(),s.getTenantId()).orElseThrow(()->new AuthenticationException("Session user is unavailable."));if(!u.canAuthenticateAt(now)){s.revoke("ACCOUNT_UNAVAILABLE",now);throw new AuthenticationException("Account is not available for authentication.");}if(mfa.enabled(u.getTenantId(),u.getId())&&!s.isMfaVerified()){s.revoke("MFA_REQUIRED",now);throw new AuthenticationException("MFA verification is required.");}return issue(u,s,now,s.isMfaVerified(),s.isTrustedDevice());}
 @Transactional public void logout(LogoutCommand cmd){sessions.findByRefreshTokenHash(refreshTokens.hash(cmd.refreshToken())).ifPresent(s->s.revoke("LOGOUT",Instant.now()));}
 private UserAccount findUser(UUID tenant,String identity){return users.findByTenantIdAndUsernameIgnoreCase(tenant,identity).or(()->users.findByTenantIdAndEmailIgnoreCase(tenant,identity)).orElseThrow(()->new AuthenticationException("Invalid username or password."));}
 private TokenResponse issue(UserAccount u,UserSession existing,Instant now,boolean mfaVerified,boolean trusted){var a=authorities.resolve(u.getTenantId(),u.getId());String raw=refreshTokens.generate();Instant refreshExp=now.plusSeconds(props.refreshTokenSeconds());UserSession s=existing;if(s==null){s=new UserSession(u.getId(),refreshTokens.hash(raw),refreshExp,now);s.setTenantId(u.getTenantId());if(mfaVerified)s.markMfaVerified(trusted);sessions.save(s);}else{s.rotate(refreshTokens.hash(raw),refreshExp,now);}GtPrincipal p=new GtPrincipal(u.getId(),u.getUsername(),u.getTenantId(),a.roles(),a.permissions(),s.getId());String access=jwt.issueAccessToken(p,s.getAuthenticationAssurance());return new TokenResponse("Bearer",access,now.plusSeconds(jwtProps.accessTokenSeconds()),raw,refreshExp,s.getId(),u.getId(),u.getTenantId(),u.getUsername(),a.roles(),a.permissions());}
 private UUID tenant(){return RequestContextHolder.current().map(c->c.tenantId()).filter(v->v!=null&&!v.isBlank()).map(UUID::fromString).orElseThrow(()->new AuthenticationException("X-Tenant-ID header is required."));}
}
