package africa.growtogether.platform.ewe;
import static africa.growtogether.platform.ewe.WorkflowDtos.*; import africa.growtogether.platform.common.api.*; import jakarta.validation.Valid; import java.net.URI; import java.util.*; import org.springframework.http.ResponseEntity; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/workflows") public class WorkflowController {private final WorkflowService service;private final ApiResponses responses;public WorkflowController(WorkflowService s,ApiResponses r){service=s;responses=r;}
 @PostMapping("/definitions") @PreAuthorize("hasAuthority('workflow.definition.create')") public ResponseEntity<ApiResponse<DefinitionView>> createDefinition(@Valid @RequestBody CreateDefinition c){DefinitionView v=service.createDefinition(c);return ResponseEntity.created(URI.create("/api/v1/workflows/definitions/"+v.id())).body(responses.success("GT-EWE-001","Workflow definition created.",v));}
 @GetMapping("/definitions") @PreAuthorize("hasAuthority('workflow.definition.read')") public ApiResponse<List<DefinitionView>> definitions(){return responses.success("GT-EWE-002","Workflow definitions retrieved.",service.listDefinitions());}
 @PostMapping("/definitions/{id}/versions") @PreAuthorize("hasAuthority('workflow.definition.update')") public ApiResponse<VersionView> createVersion(@PathVariable UUID id,@Valid @RequestBody CreateVersion c){return responses.success("GT-EWE-003","Workflow version created.",service.createVersion(id,c));}
 @GetMapping("/definitions/{id}/versions") @PreAuthorize("hasAuthority('workflow.definition.read')") public ApiResponse<List<VersionView>> versions(@PathVariable UUID id){return responses.success("GT-EWE-004","Workflow versions retrieved.",service.listVersions(id));}
 @PostMapping("/instances") @PreAuthorize("hasAuthority('workflow.instance.start')") public ResponseEntity<ApiResponse<InstanceView>> start(@Valid @RequestBody StartWorkflow c){InstanceView v=service.start(c);return ResponseEntity.created(URI.create("/api/v1/workflows/instances/"+v.id())).body(responses.success("GT-EWE-101","Workflow instance started.",v));}
 @GetMapping("/instances/{id}") @PreAuthorize("hasAuthority('workflow.instance.read')") public ApiResponse<InstanceView> get(@PathVariable UUID id){return responses.success("GT-EWE-102","Workflow instance retrieved.",service.get(id));}
 @PostMapping("/instances/{id}/advance") @PreAuthorize("hasAuthority('workflow.instance.execute')") public ApiResponse<InstanceView> advance(@PathVariable UUID id,@Valid @RequestBody AdvanceWorkflow c){return responses.success("GT-EWE-103","Workflow advanced.",service.advance(id,c));}
 @PostMapping("/instances/{id}/resume") @PreAuthorize("hasAuthority('workflow.instance.execute')") public ApiResponse<InstanceView> resume(@PathVariable UUID id){return responses.success("GT-EWE-104","Workflow resumed.",service.resume(id));}
 @PostMapping("/instances/{id}/complete") @PreAuthorize("hasAuthority('workflow.instance.execute')") public ApiResponse<InstanceView> complete(@PathVariable UUID id){return responses.success("GT-EWE-105","Workflow completed.",service.complete(id));}
 @PostMapping("/instances/{id}/fail") @PreAuthorize("hasAuthority('workflow.instance.execute')") public ApiResponse<InstanceView> fail(@PathVariable UUID id,@Valid @RequestBody FailWorkflow c){return responses.success("GT-EWE-106","Workflow marked failed.",service.fail(id,c));}
 @PostMapping("/instances/{id}/retry") @PreAuthorize("hasAuthority('workflow.instance.retry')") public ApiResponse<InstanceView> retry(@PathVariable UUID id){return responses.success("GT-EWE-107","Workflow retried.",service.retry(id));}
 @PostMapping("/instances/{id}/cancel") @PreAuthorize("hasAuthority('workflow.instance.cancel')") public ApiResponse<InstanceView> cancel(@PathVariable UUID id){return responses.success("GT-EWE-108","Workflow cancelled.",service.cancel(id));}
 @PostMapping("/instances/{id}/restart") @PreAuthorize("hasAuthority('workflow.instance.restart')") public ApiResponse<InstanceView> restart(@PathVariable UUID id,@Valid @RequestBody RestartWorkflow c){return responses.success("GT-EWE-109","Workflow restarted.",service.restart(id,c));}
 @PutMapping("/instances/{id}/variables") @PreAuthorize("hasAuthority('workflow.instance.execute')") public ApiResponse<VariableView> variable(@PathVariable UUID id,@Valid @RequestBody SetVariable c){return responses.success("GT-EWE-110","Workflow variable stored.",service.setVariable(id,c));}
 @GetMapping("/instances/{id}/variables") @PreAuthorize("hasAuthority('workflow.instance.read')") public ApiResponse<List<VariableView>> variables(@PathVariable UUID id,@RequestParam(defaultValue="false") boolean reveal){return responses.success("GT-EWE-111","Workflow variables retrieved.",service.getVariables(id,reveal));}
 @GetMapping("/instances/{id}/history") @PreAuthorize("hasAuthority('workflow.instance.read')") public ApiResponse<List<EventView>> history(@PathVariable UUID id){return responses.success("GT-EWE-112","Workflow history retrieved.",service.history(id));}
}
