package africa.growtogether.platform.ewe;
import static africa.growtogether.platform.ewe.WorkflowDtos.*;
import africa.growtogether.platform.common.security.EnterpriseIdentityContext; import africa.growtogether.platform.ewe.integration.EweAuditRecorder; import com.fasterxml.jackson.databind.ObjectMapper; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class WorkflowService {
 private final WorkflowDefinitionRepository definitions; private final WorkflowVersionRepository versions; private final WorkflowInstanceRepository instances; private final WorkflowVariableRepository variables; private final WorkflowExecutionEventRepository events; private final ObjectMapper mapper; private final EnterpriseIdentityContext identity; private final EweAuditRecorder audit;
 public WorkflowService(WorkflowDefinitionRepository d,WorkflowVersionRepository v,WorkflowInstanceRepository i,WorkflowVariableRepository vars,WorkflowExecutionEventRepository e,ObjectMapper m,EnterpriseIdentityContext identity,EweAuditRecorder audit){definitions=d;versions=v;instances=i;variables=vars;events=e;mapper=m;this.identity=identity;this.audit=audit;}
 private UUID tenant(){return identity.tenantId();}
 @Transactional public DefinitionView createDefinition(CreateDefinition c){UUID t=tenant();String code=WorkflowDefinition.normalize(c.code());if(definitions.findByTenantIdAndCode(t,code).isPresent())throw new WorkflowException("Workflow definition code already exists.");WorkflowDefinition d=new WorkflowDefinition(code,c.name(),c.category(),c.description());return DefinitionView.from(definitions.save(d));}
 @Transactional(readOnly=true) public List<DefinitionView> listDefinitions(){return definitions.findAllByTenantIdOrderByCode(tenant()).stream().map(DefinitionView::from).toList();}
 @Transactional public VersionView createVersion(UUID definitionId,CreateVersion c){UUID t=tenant();WorkflowDefinition d=definition(definitionId,t);int number=Math.toIntExact(versions.countByDefinitionIdAndTenantId(definitionId,t)+1);WorkflowVersion v=new WorkflowVersion(definitionId,number,c.definitionJson(),sha256(c.definitionJson()));if(c.activate()){v.publish();d.activate(number);definitions.save(d);}return VersionView.from(versions.save(v));}
 @Transactional(readOnly=true) public List<VersionView> listVersions(UUID definitionId){UUID t=tenant();definition(definitionId,t);return versions.findAllByDefinitionIdAndTenantIdOrderByVersionNumberDesc(definitionId,t).stream().map(VersionView::from).toList();}
 @Transactional public InstanceView start(StartWorkflow c){UUID t=tenant();WorkflowDefinition d=definition(c.definitionId(),t);int version=c.version()!=null?c.version():Optional.ofNullable(d.getActiveVersion()).orElseThrow(()->new WorkflowException("Workflow definition has no active version."));WorkflowVersion v=versions.findByDefinitionIdAndTenantIdAndVersionNumber(d.getId(),t,version).orElseThrow(()->new WorkflowException("Workflow version not found."));if(!v.isPublished())throw new WorkflowException("Only published workflow versions may be started.");WorkflowInstance i=new WorkflowInstance(d.getId(),version,c.businessKey(),c.executionContext(),null);i.start(c.firstStep());instances.save(i);if(c.variables()!=null)c.variables().forEach((k,val)->saveVariable(i,k,toJson(val),false));event(i,WorkflowEventType.STARTED,c.firstStep(),"Workflow started.","{}");audit.workflow("EWE.WORKFLOW.STARTED",i.getId(),"Workflow started",Map.of("definitionId",d.getId().toString(),"version",version));return InstanceView.from(i);}
 @Transactional public InstanceView advance(UUID id,AdvanceWorkflow c){WorkflowInstance i=instance(id);if(c.waiting()){i.waitAt(c.nextStep());event(i,WorkflowEventType.WAITING,c.nextStep(),"Workflow is waiting.","{}");}else{i.advance(c.nextStep(),c.executionContext());event(i,WorkflowEventType.STEP_ADVANCED,c.nextStep(),"Workflow advanced.","{}");}return InstanceView.from(instances.save(i));}
 @Transactional public InstanceView resume(UUID id){WorkflowInstance i=instance(id);i.resume();event(i,WorkflowEventType.RESUMED,i.getCurrentStep(),"Workflow resumed.","{}");return InstanceView.from(instances.save(i));}
 @Transactional public InstanceView complete(UUID id){WorkflowInstance i=instance(id);i.complete();event(i,WorkflowEventType.COMPLETED,null,"Workflow completed.","{}");audit.workflow("EWE.WORKFLOW.COMPLETED",i.getId(),"Workflow completed",Map.of());return InstanceView.from(instances.save(i));}
 @Transactional public InstanceView fail(UUID id,FailWorkflow c){WorkflowInstance i=instance(id);i.fail(c.reason());event(i,WorkflowEventType.FAILED,i.getCurrentStep(),c.reason(),"{}");audit.failure("EWE.WORKFLOW.FAILED",i.getId(),c.reason());return InstanceView.from(instances.save(i));}
 @Transactional public InstanceView retry(UUID id){WorkflowInstance i=instance(id);i.retry();event(i,WorkflowEventType.RETRIED,i.getCurrentStep(),"Workflow retried.","{}");return InstanceView.from(instances.save(i));}
 @Transactional public InstanceView cancel(UUID id){WorkflowInstance i=instance(id);i.cancel();event(i,WorkflowEventType.CANCELLED,null,"Workflow cancelled.","{}");return InstanceView.from(instances.save(i));}
 @Transactional public InstanceView restart(UUID id,RestartWorkflow c){WorkflowInstance source=instance(id);WorkflowInstance copy=new WorkflowInstance(source.getDefinitionId(),source.getDefinitionVersion(),c.businessKey(),c.executionContext()==null?source.getExecutionContext():c.executionContext(),source.getId());copy.start(c.firstStep());instances.save(copy);variables.findAllByInstanceIdAndTenantIdOrderByKey(source.getId(),tenant()).forEach(v->saveVariable(copy,v.getKey(),v.getValue(),v.isSensitive()));event(copy,WorkflowEventType.RESTARTED,c.firstStep(),"Workflow restarted from "+source.getId()+".","{}");return InstanceView.from(copy);}
 @Transactional public VariableView setVariable(UUID id,SetVariable c){WorkflowInstance i=instance(id);WorkflowVariable v=variables.findByInstanceIdAndTenantIdAndKey(id,tenant(),WorkflowDefinition.normalize(c.key())).orElseGet(()->new WorkflowVariable(id,c.key(),c.value(),c.sensitive()));v.update(c.value(),c.sensitive());variables.save(v);event(i,WorkflowEventType.VARIABLE_SET,i.getCurrentStep(),"Workflow variable updated.","{\"key\":\""+v.getKey()+"\"}");return VariableView.from(v,false);}
 @Transactional(readOnly=true) public InstanceView get(UUID id){return InstanceView.from(instance(id));}
 @Transactional(readOnly=true) public List<VariableView> getVariables(UUID id,boolean reveal){instance(id);return variables.findAllByInstanceIdAndTenantIdOrderByKey(id,tenant()).stream().map(v->VariableView.from(v,reveal)).toList();}
 @Transactional(readOnly=true) public List<EventView> history(UUID id){instance(id);return events.findAllByInstanceIdAndTenantIdOrderByOccurredAtAsc(id,tenant()).stream().map(EventView::from).toList();}
 private WorkflowDefinition definition(UUID id,UUID t){return definitions.findByIdAndTenantId(id,t).orElseThrow(()->new WorkflowException("Workflow definition not found."));}
 private WorkflowInstance instance(UUID id){return instances.findByIdAndTenantId(id,tenant()).orElseThrow(()->new WorkflowException("Workflow instance not found."));}
 private void saveVariable(WorkflowInstance i,String key,String value,boolean sensitive){variables.save(new WorkflowVariable(i.getId(),key,value,sensitive));}
 private void event(WorkflowInstance i,WorkflowEventType type,String step,String message,String details){events.save(new WorkflowExecutionEvent(tenant(),i.getId(),type,step,message,details));}
 private String toJson(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new WorkflowException("Workflow variable is not JSON serializable.");}}
 private static String sha256(String value){try{byte[] hash=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(hash);}catch(Exception e){throw new IllegalStateException(e);}}
}
