package africa.growtogether.platform.eaif;
import africa.growtogether.platform.eaif.integration.*;
import java.util.Map; import java.util.UUID; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional
public class AiFoundationService {
 private final AiProviderRepository providers; private final AiModelRepository models; private final PromptTemplateRepository prompts; private final AiRequestRepository requests; private final AiSafetyPolicy safety; private final EaifAuditRecorder audit; private final EaifPlatformIntegrationGateway platform;
 public AiFoundationService(AiProviderRepository p,AiModelRepository m,PromptTemplateRepository t,AiRequestRepository r,AiSafetyPolicy s,EaifAuditRecorder a,EaifPlatformIntegrationGateway g){providers=p;models=m;prompts=t;requests=r;safety=s;audit=a;platform=g;}
 public AiProvider createProvider(UUID tenantId,CreateProviderRequest q){if(providers.findByTenantIdAndCode(tenantId,q.code().trim().toUpperCase()).isPresent())throw new IllegalStateException("Provider code already exists");return providers.save(new AiProvider(tenantId,q.code(),q.name(),q.type()));}
 public AiModel createModel(UUID tenantId,CreateModelRequest q){providers.findByTenantIdAndCode(tenantId,q.providerCode().trim().toUpperCase()).orElseThrow(()->new IllegalArgumentException("Provider not found"));return models.save(new AiModel(tenantId,q.code(),q.providerCode(),q.providerModel(),q.capability()));}
 public PromptTemplate createPrompt(UUID tenantId,CreatePromptRequest q){return prompts.save(new PromptTemplate(tenantId,q.code(),q.version(),q.userTemplate()));}
 public AiRequest submit(UUID tenantId,CreateAiRequest q){models.findByTenantIdAndCode(tenantId,q.modelCode().trim().toUpperCase()).orElseThrow(()->new IllegalArgumentException("Model not found"));AiRequest r=new AiRequest(tenantId,q.sourceService(),q.useCase(),q.modelCode(),q.inputHash(),q.riskLevel(),q.correlationId());safety.validate(r);r.approve();r=requests.save(r);audit.success("EAIF.REQUEST.SUBMITTED",r.getId().toString(),"AI request submitted",Map.of("modelCode",r.modelCode(),"riskLevel",r.riskLevel().name(),"sourceService",r.sourceService()));platform.publishAnalytics(r.getId(),r.requestStatus().name(),r.modelCode(),r.riskLevel().name());return r;}
 public AiRequest begin(UUID tenantId,UUID id){AiRequest r=get(tenantId,id);r.begin();audit.success("EAIF.REQUEST.PROCESSING",id.toString(),"AI request processing started",Map.of("modelCode",r.modelCode()));platform.publishAnalytics(id,r.requestStatus().name(),r.modelCode(),r.riskLevel().name());return r;}
 public AiRequest succeed(UUID tenantId,UUID id,String ref){AiRequest r=get(tenantId,id);r.succeed(ref);audit.success("EAIF.REQUEST.SUCCEEDED",id.toString(),"AI request succeeded",Map.of("modelCode",r.modelCode(),"outputReferencePresent",ref!=null&&!ref.isBlank()));platform.publishAnalytics(id,r.requestStatus().name(),r.modelCode(),r.riskLevel().name());return r;}
 public AiRequest fail(UUID tenantId,UUID id,String reason){AiRequest r=get(tenantId,id);r.fail(reason);audit.failure("EAIF.REQUEST.FAILED",id.toString(),"AI request failed",Map.of("modelCode",r.modelCode(),"reasonCode","PROVIDER_OR_RUNTIME_FAILURE"));platform.publishAnalytics(id,r.requestStatus().name(),r.modelCode(),r.riskLevel().name());return r;}
 @Transactional(readOnly=true) public AiRequest get(UUID tenantId,UUID id){return requests.findByIdAndTenantId(id,tenantId).orElseThrow(()->new IllegalArgumentException("AI request not found"));}
}
