package africa.growtogether.platform.eip.payment;
import africa.growtogether.platform.common.security.EnterpriseIdentityContext; import static africa.growtogether.platform.eip.payment.PaymentDtos.*; import java.util.UUID; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class PaymentService {private final EnterpriseIdentityContext identity;private final PaymentTransactionRepository transactions;private final PaymentProviderAttemptRepository attempts;private final PaymentSettlementRepository settlements;private final PaymentReconciliationRepository reconciliations;private final PaymentDisputeRepository disputes;
 public PaymentService(EnterpriseIdentityContext identity,PaymentTransactionRepository transactions,PaymentProviderAttemptRepository attempts,PaymentSettlementRepository settlements,PaymentReconciliationRepository reconciliations,PaymentDisputeRepository disputes){this.identity=identity;this.transactions=transactions;this.attempts=attempts;this.settlements=settlements;this.reconciliations=reconciliations;this.disputes=disputes;}
 @Transactional public PaymentView create(CreatePayment c){var existing=transactions.findByTenantIdAndIdempotencyKey(identity.tenantId(),c.idempotencyKey());if(existing.isPresent())return PaymentView.from(existing.get());var p=new PaymentTransaction(identity.tenantId(),c.merchantReference(),c.payerReference(),c.amount(),c.currency(),c.channel(),c.connectorCode(),c.idempotencyKey());p.submit();return PaymentView.from(transactions.save(p));}
 @Transactional(readOnly=true) public PaymentView get(UUID id){return PaymentView.from(load(id));}
 @Transactional public PaymentView submitted(UUID id,String providerRequestId){var p=load(id);long count=attempts.countByTenantIdAndPaymentTransactionId(identity.tenantId(),id);var a=new PaymentProviderAttempt(identity.tenantId(),id,(int)count+1,p.connectorCode());a.submitted(providerRequestId);attempts.save(a);return PaymentView.from(p);}
 @Transactional public PaymentView succeed(UUID id,ProviderResult r){var p=load(id);p.succeed(r.providerReference());return PaymentView.from(transactions.save(p));}
 @Transactional public PaymentView fail(UUID id,Failure f){var p=load(id);p.fail(f.code(),f.message());return PaymentView.from(transactions.save(p));}
 @Transactional public PaymentView cancel(UUID id){var p=load(id);p.cancel();return PaymentView.from(transactions.save(p));}
 @Transactional public PaymentView reverse(UUID id){var p=load(id);p.reverse();return PaymentView.from(transactions.save(p));}
 @Transactional public SettlementView settlement(SettlementCommand c){return SettlementView.from(settlements.save(new PaymentSettlement(identity.tenantId(),c.connectorCode(),c.providerSettlementReference(),c.settlementDate(),c.grossAmount(),c.feeAmount(),c.currency())));}
 @Transactional public ReconciliationView reconcile(ReconcileCommand c){var p=load(c.paymentTransactionId());var s=settlements.findByTenantIdAndId(identity.tenantId(),c.settlementId()).orElseThrow(()->new IllegalArgumentException("Settlement not found"));var r=new PaymentReconciliation(identity.tenantId(),p.id(),s.id(),c.providerReference(),p.amount(),c.providerAmount());if(r.status()==ReconciliationStatus.MATCHED)s.matched();return ReconciliationView.from(reconciliations.save(r));}
 @Transactional public UUID dispute(DisputeCommand c){load(c.paymentTransactionId());return disputes.save(new PaymentDispute(identity.tenantId(),c.paymentTransactionId(),c.reasonCode(),c.description())).id();}
 private PaymentTransaction load(UUID id){return transactions.findByTenantIdAndId(identity.tenantId(),id).orElseThrow(()->new IllegalArgumentException("Payment not found"));}
}
