package africa.growtogether.platform.eip.payment;
enum PaymentChannel { MOBILE_MONEY, BANK_TRANSFER, CARD, CASH_REFERENCE, WALLET }
enum PaymentTransactionStatus { CREATED, PENDING_PROVIDER, AUTHORIZED, SUCCEEDED, FAILED, CANCELLED, REVERSED, PARTIALLY_REFUNDED, REFUNDED }
enum ProviderAttemptStatus { CREATED, SUBMITTED, ACCEPTED, FAILED, TIMED_OUT }
enum SettlementStatus { EXPECTED, RECEIVED, PARTIALLY_MATCHED, MATCHED, EXCEPTION }
enum ReconciliationStatus { UNMATCHED, MATCHED, AMOUNT_MISMATCH, DUPLICATE, MISSING_INTERNAL, MISSING_PROVIDER }
enum DisputeStatus { OPEN, UNDER_REVIEW, RESOLVED, REJECTED }
