package africa.growtogether.platform.ecs;
import africa.growtogether.platform.common.api.*; import jakarta.validation.Valid; import java.net.URI; import java.util.*; import org.springframework.http.ResponseEntity; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import static africa.growtogether.platform.ecs.ConfigurationDtos.*;
@RestController @RequestMapping("/api/v1/configuration") public class ConfigurationController {private final ConfigurationService service;private final ApiResponses responses;public ConfigurationController(ConfigurationService s,ApiResponses r){service=s;responses=r;}
 @PostMapping("/definitions") @PreAuthorize("hasAuthority('platform.configuration.manage')") public ResponseEntity<ApiResponse<DefinitionView>> create(@Valid @RequestBody UpsertDefinition c){DefinitionView v=service.create(c);return ResponseEntity.created(URI.create("/api/v1/configuration/definitions/"+v.id())).body(responses.success("GT-ECS-001","Configuration definition created.",v));}
 @GetMapping("/definitions") @PreAuthorize("hasAuthority('platform.configuration.read')") public ApiResponse<List<DefinitionView>> list(){return responses.success("GT-ECS-002","Configuration definitions retrieved.",service.list());}
 @PutMapping("/definitions/{id}") @PreAuthorize("hasAuthority('platform.configuration.manage')") public ApiResponse<DefinitionView> update(@PathVariable UUID id,@Valid @RequestBody UpsertDefinition c){return responses.success("GT-ECS-003","Configuration definition updated.",service.update(id,c));}
 @PutMapping("/definitions/{id}/values") @PreAuthorize("hasAuthority('platform.configuration.manage')") public ApiResponse<ResolvedValue> put(@PathVariable UUID id,@Valid @RequestBody PutValue c){return responses.success("GT-ECS-004","Configuration value stored.",service.put(id,c));}
 @PostMapping("/resolve") @PreAuthorize("hasAuthority('platform.configuration.read')") public ApiResponse<ResolvedValue> resolve(@Valid @RequestBody ResolveRequest r){return responses.success("GT-ECS-005","Configuration resolved.",service.resolve(r));}
 @GetMapping("/values/{valueId}/history") @PreAuthorize("hasAuthority('platform.configuration.history.read')") public ApiResponse<List<VersionView>> history(@PathVariable UUID valueId){return responses.success("GT-ECS-006","Configuration history retrieved.",service.history(valueId));}
 @PostMapping("/values/{valueId}/rollback") @PreAuthorize("hasAuthority('platform.configuration.rollback')") public ApiResponse<ResolvedValue> rollback(@PathVariable UUID valueId,@Valid @RequestBody RollbackRequest request){return responses.success("GT-ECS-007","Configuration rolled back.",service.rollback(valueId,request));}
}
