package africa.growtogether.platform.ewe.task;
import africa.growtogether.platform.common.persistence.AuditedTenantEntity; import jakarta.persistence.*; import java.time.*; import java.util.UUID;
@Entity @Table(name="ewe_tasks",indexes={@Index(name="ix_ewe_task_tenant_status",columnList="tenant_id,task_status"),@Index(name="ix_ewe_task_assignee",columnList="tenant_id,assignee_user_id"),@Index(name="ix_ewe_task_instance",columnList="tenant_id,instance_id")})
public class WorkflowTask extends AuditedTenantEntity {
 @Column(name="instance_id",nullable=false,updatable=false) private UUID instanceId; @Column(name="task_key",nullable=false,length=120) private String taskKey; @Column(name="name",nullable=false,length=180) private String name;
 @Enumerated(EnumType.STRING) @Column(name="task_type",nullable=false,length=20) private TaskType taskType; @Enumerated(EnumType.STRING) @Column(name="task_status",nullable=false,length=20) private TaskStatus taskStatus=TaskStatus.CREATED;
 @Enumerated(EnumType.STRING) @Column(name="assignment_type",nullable=false,length=20) private AssignmentType assignmentType=AssignmentType.UNASSIGNED; @Column(name="assignee_user_id") private UUID assigneeUserId; @Column(name="assignee_role",length=120) private String assigneeRole; @Column(name="assignee_group",length=120) private String assigneeGroup; @Column(name="routing_expression",length=1000) private String routingExpression;
 @Column(name="claimed_by") private UUID claimedBy; @Column(name="delegated_from") private UUID delegatedFrom; @Column(name="delegated_to") private UUID delegatedTo; @Column(name="due_at") private Instant dueAt; @Column(name="escalation_at") private Instant escalationAt; @Column(name="completed_at") private Instant completedAt; @Column(name="outcome",length=40) private String outcome; @Column(name="completion_comment",length=1000) private String completionComment;
 protected WorkflowTask(){} public WorkflowTask(UUID instanceId,String taskKey,String name,TaskType type){this.instanceId=instanceId;this.taskKey=norm(taskKey);this.name=req(name);this.taskType=type;}
 public void assignUser(UUID user){ensureOpen();assignmentType=AssignmentType.USER;assigneeUserId=user;assigneeRole=null;assigneeGroup=null;routingExpression=null;taskStatus=TaskStatus.ASSIGNED;}
 public void assignRole(String role){ensureOpen();assignmentType=AssignmentType.ROLE;assigneeRole=norm(role);assigneeUserId=null;assigneeGroup=null;routingExpression=null;taskStatus=TaskStatus.ASSIGNED;}
 public void assignGroup(String group){ensureOpen();assignmentType=AssignmentType.GROUP;assigneeGroup=norm(group);assigneeUserId=null;assigneeRole=null;routingExpression=null;taskStatus=TaskStatus.ASSIGNED;}
 public void assignExpression(String expression){ensureOpen();assignmentType=AssignmentType.EXPRESSION;routingExpression=req(expression);taskStatus=TaskStatus.ASSIGNED;}
 public void claim(UUID user){if(taskStatus!=TaskStatus.ASSIGNED&&taskStatus!=TaskStatus.CREATED)throw new IllegalStateException("Task cannot be claimed from "+taskStatus);claimedBy=user;assigneeUserId=user;assignmentType=AssignmentType.USER;taskStatus=TaskStatus.CLAIMED;}
 public void start(){if(taskStatus!=TaskStatus.CLAIMED&&taskStatus!=TaskStatus.ASSIGNED)throw new IllegalStateException("Task cannot start from "+taskStatus);taskStatus=TaskStatus.IN_PROGRESS;}
 public void complete(String outcome,String comment){if(taskStatus!=TaskStatus.IN_PROGRESS&&taskStatus!=TaskStatus.CLAIMED&&taskStatus!=TaskStatus.ASSIGNED)throw new IllegalStateException("Task cannot complete from "+taskStatus);this.outcome=outcome;this.completionComment=comment;taskStatus=TaskStatus.COMPLETED;completedAt=Instant.now();}
 public void decide(ApprovalDecision d,String comment){if(taskType!=TaskType.APPROVAL&&taskType!=TaskType.REVIEW)throw new IllegalStateException("Task is not an approval/review task");complete(d.name(),comment);if(d==ApprovalDecision.REJECT) taskStatus=TaskStatus.REJECTED;}
 public void delegate(UUID from,UUID to){ensureOpen();delegatedFrom=from;delegatedTo=to;assignUser(to);}
 public void setSla(Instant due,Instant escalation){if(escalation!=null&&due!=null&&escalation.isBefore(due))throw new IllegalArgumentException("Escalation time cannot be before due time");dueAt=due;escalationAt=escalation;}
 public void escalate(UUID to){ensureOpen();taskStatus=TaskStatus.ESCALATED;if(to!=null)assignUser(to);}
 public void cancel(){ensureOpen();taskStatus=TaskStatus.CANCELLED;completedAt=Instant.now();}
 private void ensureOpen(){if(taskStatus==TaskStatus.COMPLETED||taskStatus==TaskStatus.REJECTED||taskStatus==TaskStatus.CANCELLED||taskStatus==TaskStatus.EXPIRED)throw new IllegalStateException("Task is terminal");}
 private static String req(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("Value is required");return v.trim();} private static String norm(String v){return req(v).trim().toUpperCase().replace(' ','_');}
 public UUID getInstanceId(){return instanceId;} public String getTaskKey(){return taskKey;} public String getName(){return name;} public TaskType getTaskType(){return taskType;} public TaskStatus getTaskStatus(){return taskStatus;} public AssignmentType getAssignmentType(){return assignmentType;} public UUID getAssigneeUserId(){return assigneeUserId;} public String getAssigneeRole(){return assigneeRole;} public String getAssigneeGroup(){return assigneeGroup;} public String getRoutingExpression(){return routingExpression;} public UUID getClaimedBy(){return claimedBy;} public UUID getDelegatedFrom(){return delegatedFrom;} public UUID getDelegatedTo(){return delegatedTo;} public Instant getDueAt(){return dueAt;} public Instant getEscalationAt(){return escalationAt;} public Instant getCompletedAt(){return completedAt;} public String getOutcome(){return outcome;} public String getCompletionComment(){return completionComment;}
}