package africa.growtogether.platform.eap.advanced;
import africa.growtogether.platform.common.security.EnterpriseIdentityContext; import africa.growtogether.platform.eap.integration.EapAuditRecorder; import africa.growtogether.platform.eap.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class AdvancedAnalyticsService {
 private final EnterpriseIdentityContext identity; private final EapAuditRecorder audit; private final AlertRuleRepository rules; private final AnalyticsAlertRepository alerts; private final ReportScheduleRepository schedules; private final AnalyticsDataSourceRepository sources; private final MetricAggregateRepository aggregates; private final ReportExecutionRepository reports; private final AdvancedAnalyticsIntegrationGateway gateway;
 public AdvancedAnalyticsService(EnterpriseIdentityContext identity,EapAuditRecorder audit,AlertRuleRepository rules,AnalyticsAlertRepository alerts,ReportScheduleRepository schedules,AnalyticsDataSourceRepository sources,MetricAggregateRepository aggregates,ReportExecutionRepository reports,AdvancedAnalyticsIntegrationGateway gateway){this.identity=identity;this.audit=audit;this.rules=rules;this.alerts=alerts;this.schedules=schedules;this.sources=sources;this.aggregates=aggregates;this.reports=reports;this.gateway=gateway;}
 @Transactional public UUID createAlertRule(AdvancedAnalyticsDtos.CreateAlertRule r){UUID tenant=identity.requireTenantId();if(rules.findByTenantIdAndRuleCode(tenant,r.code().toUpperCase(Locale.ROOT)).isPresent())throw new IllegalStateException("Alert rule code already exists");return rules.save(new AlertRule(tenant,r.code(),r.name(),r.metricCode(),r.operator(),r.threshold(),r.severity(),r.cooldownSeconds())).getId();}
 @Transactional public List<UUID> evaluate(AdvancedAnalyticsDtos.EvaluateAlerts r){UUID tenant=identity.requireTenantId();List<UUID> ids=new ArrayList<>();for(AlertRule rule:rules.findByTenantIdAndMetricCodeAndActiveTrue(tenant,r.metricCode().toUpperCase(Locale.ROOT)))if(rule.matches(r.observedValue())){AnalyticsAlert alert=alerts.save(new AnalyticsAlert(tenant,rule,r.observedValue()));gateway.publishAlert(tenant,alert.getId(),rule.metricCode(),rule.severity());audit.success("ANALYTICS.ALERT.TRIGGERED","ANALYTICS_ALERT",alert.getId().toString(),"Analytics alert triggered",Map.of("metricCode",rule.metricCode(),"severity",rule.severity().name()));ids.add(alert.getId());}return ids;}
 @Transactional public void acknowledge(UUID id){AnalyticsAlert a=alerts.findById(id).filter(x->x.getTenantId().equals(identity.requireTenantId())).orElseThrow();a.acknowledge();}
 @Transactional public void resolve(UUID id){AnalyticsAlert a=alerts.findById(id).filter(x->x.getTenantId().equals(identity.requireTenantId())).orElseThrow();a.resolve();}
 @Transactional public UUID createSchedule(AdvancedAnalyticsDtos.CreateSchedule r){return schedules.save(new ReportSchedule(identity.requireTenantId(),r.code(),r.reportCode(),r.cronExpression(),r.timezone(),r.deliveryChannel(),r.recipientsJson(),r.parametersJson(),r.nextRunAt())).getId();}
 @Transactional public int runDueSchedules(){UUID tenant=identity.requireTenantId();int count=0;Instant now=Instant.now();for(ReportSchedule s:schedules.findTop100ByTenantIdAndStatusAndNextRunAtLessThanEqualOrderByNextRunAt(tenant,AdvancedAnalyticsEnums.ScheduleStatus.ACTIVE,now)){ReportExecution execution=reports.save(new ReportExecution(tenant,s.reportCode(),s.parametersJson(),AnalyticsEnums.ExportFormat.JSON));gateway.deliverScheduledReport(tenant,execution.getId(),s.reportCode(),s.deliveryChannel(),s.recipientsJson());audit.success("ANALYTICS.REPORT.SCHEDULED","REPORT_EXECUTION",execution.getId().toString(),"Scheduled analytics report dispatched",Map.of("reportCode",s.reportCode(),"channel",s.deliveryChannel().name()));s.markRun(now.plus(Duration.ofDays(1)));count++;}return count;}
 @Transactional public UUID createDataSource(AdvancedAnalyticsDtos.CreateDataSource r){UUID tenant=identity.requireTenantId();if(sources.findByTenantIdAndSourceCode(tenant,r.code().toUpperCase(Locale.ROOT)).isPresent())throw new IllegalStateException("Data source code already exists");return sources.save(new AnalyticsDataSource(tenant,r.code(),r.name(),r.type(),r.sourceService(),r.configurationReference(),r.schemaJson())).getId();}
 @Transactional(readOnly=true) public AdvancedAnalyticsDtos.TrendResult trend(String metric,Instant from,Instant to){List<MetricAggregate> points=aggregates.findByTenantIdAndMetricCodeAndBucketStartBetweenOrderByBucketStart(identity.requireTenantId(),metric.toUpperCase(Locale.ROOT),from,to);if(points.size()<2)return new AdvancedAnalyticsDtos.TrendResult(metric,from,to,AdvancedAnalyticsEnums.TrendDirection.INSUFFICIENT_DATA,BigDecimal.ZERO,BigDecimal.ZERO,points.size());BigDecimal first=points.get(0).average(),last=points.get(points.size()-1).average(),change=last.subtract(first);BigDecimal pct=first.compareTo(BigDecimal.ZERO)==0?BigDecimal.ZERO:change.multiply(BigDecimal.valueOf(100)).divide(first.abs(),4,RoundingMode.HALF_UP);AdvancedAnalyticsEnums.TrendDirection d=change.abs().compareTo(new BigDecimal("0.0001"))<=0?AdvancedAnalyticsEnums.TrendDirection.STABLE:change.signum()>0?AdvancedAnalyticsEnums.TrendDirection.RISING:AdvancedAnalyticsEnums.TrendDirection.FALLING;return new AdvancedAnalyticsDtos.TrendResult(metric,from,to,d,change,pct,points.size());}
}
