package africa.growtogether.platform.eap.advanced;
import africa.growtogether.platform.common.persistence.AuditedTenantEntity; import jakarta.persistence.*; import java.math.BigDecimal;
@Entity @Table(name="eap_alert_rules",uniqueConstraints=@UniqueConstraint(name="uq_eap_alert_rule_code",columnNames={"tenant_id","rule_code"}),indexes=@Index(name="ix_eap_alert_metric",columnList="tenant_id,metric_code,active"))
public class AlertRule extends AuditedTenantEntity {
 @Column(name="rule_code",nullable=false,length=120) private String ruleCode; @Column(name="rule_name",nullable=false,length=180) private String ruleName; @Column(name="metric_code",nullable=false,length=120) private String metricCode;
 @Enumerated(EnumType.STRING) @Column(name="operator",nullable=false,length=30) private AdvancedAnalyticsEnums.AlertOperator operator; @Column(name="threshold_value",nullable=false,precision=30,scale=8) private BigDecimal thresholdValue;
 @Enumerated(EnumType.STRING) @Column(name="severity",nullable=false,length=20) private AdvancedAnalyticsEnums.AlertSeverity severity; @Column(name="cooldown_seconds",nullable=false) private long cooldownSeconds; @Column(name="active",nullable=false) private boolean active=true;
 protected AlertRule(){} public AlertRule(java.util.UUID tenant,String code,String name,String metric,AdvancedAnalyticsEnums.AlertOperator op,BigDecimal threshold,AdvancedAnalyticsEnums.AlertSeverity severity,long cooldown){setTenantId(tenant);ruleCode=req(code).toUpperCase(java.util.Locale.ROOT);ruleName=req(name);metricCode=req(metric).toUpperCase(java.util.Locale.ROOT);operator=op==null?AdvancedAnalyticsEnums.AlertOperator.GREATER_THAN:op;thresholdValue=java.util.Objects.requireNonNull(threshold);this.severity=severity==null?AdvancedAnalyticsEnums.AlertSeverity.MEDIUM:severity;cooldownSeconds=Math.max(0,cooldown);} private static String req(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("value is required");return v.trim();}
 public String ruleCode(){return ruleCode;} public String metricCode(){return metricCode;} public BigDecimal thresholdValue(){return thresholdValue;} public AdvancedAnalyticsEnums.AlertSeverity severity(){return severity;} public long cooldownSeconds(){return cooldownSeconds;} public boolean matches(BigDecimal value){int c=value.compareTo(thresholdValue);return switch(operator){case GREATER_THAN->c>0;case GREATER_THAN_OR_EQUAL->c>=0;case LESS_THAN->c<0;case LESS_THAN_OR_EQUAL->c<=0;case EQUAL->c==0;case NOT_EQUAL->c!=0;};}
}
