package africa.growtogether.platform.eap.advanced;
import africa.growtogether.platform.common.persistence.AuditedTenantEntity; import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="eap_alerts",indexes={@Index(name="ix_eap_alert_status",columnList="tenant_id,alert_status,triggered_at"),@Index(name="ix_eap_alert_rule",columnList="tenant_id,rule_id,triggered_at")})
public class AnalyticsAlert extends AuditedTenantEntity {
 @Column(name="rule_id",nullable=false) private UUID ruleId; @Column(name="metric_code",nullable=false,length=120) private String metricCode; @Column(name="observed_value",nullable=false,precision=30,scale=8) private BigDecimal observedValue; @Column(name="threshold_value",nullable=false,precision=30,scale=8) private BigDecimal thresholdValue;
 @Enumerated(EnumType.STRING) @Column(name="severity",nullable=false,length=20) private AdvancedAnalyticsEnums.AlertSeverity severity; @Enumerated(EnumType.STRING) @Column(name="alert_status",nullable=false,length=20) private AdvancedAnalyticsEnums.AlertStatus status=AdvancedAnalyticsEnums.AlertStatus.ACTIVE; @Column(name="triggered_at",nullable=false) private Instant triggeredAt=Instant.now(); @Column(name="acknowledged_at") private Instant acknowledgedAt; @Column(name="resolved_at") private Instant resolvedAt;
 protected AnalyticsAlert(){} public AnalyticsAlert(UUID tenant,AlertRule rule,BigDecimal observed){setTenantId(tenant);ruleId=rule.getId();metricCode=rule.metricCode();observedValue=observed;thresholdValue=rule.thresholdValue();severity=rule.severity();}
 public void acknowledge(){if(status!=AdvancedAnalyticsEnums.AlertStatus.ACTIVE)throw new IllegalStateException("Only active alerts can be acknowledged");status=AdvancedAnalyticsEnums.AlertStatus.ACKNOWLEDGED;acknowledgedAt=Instant.now();} public void resolve(){if(status==AdvancedAnalyticsEnums.AlertStatus.RESOLVED)throw new IllegalStateException("Alert already resolved");status=AdvancedAnalyticsEnums.AlertStatus.RESOLVED;resolvedAt=Instant.now();} public AdvancedAnalyticsEnums.AlertStatus status(){return status;}
}
