package africa.growtogether.platform.eap.advanced;
import africa.growtogether.platform.common.persistence.AuditedTenantEntity; import jakarta.persistence.*; import java.time.Instant;
@Entity @Table(name="eap_report_schedules",uniqueConstraints=@UniqueConstraint(name="uq_eap_schedule_code",columnNames={"tenant_id","schedule_code"}),indexes=@Index(name="ix_eap_schedule_due",columnList="tenant_id,schedule_status,next_run_at"))
public class ReportSchedule extends AuditedTenantEntity {
 @Column(name="schedule_code",nullable=false,length=120) private String scheduleCode; @Column(name="report_code",nullable=false,length=120) private String reportCode; @Column(name="cron_expression",nullable=false,length=120) private String cronExpression; @Column(name="timezone",nullable=false,length=80) private String timezone;
 @Enumerated(EnumType.STRING) @Column(name="schedule_status",nullable=false,length=20) private AdvancedAnalyticsEnums.ScheduleStatus status=AdvancedAnalyticsEnums.ScheduleStatus.ACTIVE; @Enumerated(EnumType.STRING) @Column(name="delivery_channel",nullable=false,length=20) private AdvancedAnalyticsEnums.DeliveryChannel deliveryChannel; @Column(name="recipients_json",nullable=false,columnDefinition="text") private String recipientsJson; @Column(name="parameters_json",columnDefinition="text") private String parametersJson; @Column(name="next_run_at") private Instant nextRunAt; @Column(name="last_run_at") private Instant lastRunAt;
 protected ReportSchedule(){} public ReportSchedule(java.util.UUID tenant,String code,String report,String cron,String timezone,AdvancedAnalyticsEnums.DeliveryChannel channel,String recipients,String params,Instant nextRun){setTenantId(tenant);scheduleCode=req(code).toUpperCase(java.util.Locale.ROOT);reportCode=req(report).toUpperCase(java.util.Locale.ROOT);cronExpression=req(cron);this.timezone=req(timezone);deliveryChannel=channel==null?AdvancedAnalyticsEnums.DeliveryChannel.EMAIL:channel;recipientsJson=req(recipients);parametersJson=params;nextRunAt=nextRun;} private static String req(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("value is required");return v.trim();}
 public boolean due(Instant now){return status==AdvancedAnalyticsEnums.ScheduleStatus.ACTIVE&&nextRunAt!=null&&!nextRunAt.isAfter(now);} public void markRun(Instant next){lastRunAt=Instant.now();nextRunAt=next;} public String reportCode(){return reportCode;} public AdvancedAnalyticsEnums.DeliveryChannel deliveryChannel(){return deliveryChannel;} public String recipientsJson(){return recipientsJson;} public String parametersJson(){return parametersJson;}
}
